name: gcam_clone
description: A GCam like camera app with filter import support
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^5.2.5

flutter:
  uses-material-design: true
